### ISSUE TITLE
Add new colors for new clades

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/forecasts-ncov#111]
The new clades 23F and 23G have just percolated, they are now missing colors:
<img width="1914" alt="Brave Browser 2024-10-18 19 29 45" src="https://github.com/user-attachments/assets/c3af21fb-42da-441c-8543-21b53a0f434b">

**Comment by joverlee521** [comment]
Resolved by https://github.com/nextstrain/forecasts-ncov/commit/31a6163d76254ea53cd8def4e19ff6b5f8c77176. 

New colors are showing up on https://nextstrain.org/sars-cov-2/forecasts

![Screenshot 2024-10-21 at 3 34 56 PM](https://github.com/user-attachments/assets/020e0dae-221a-492f-806c-508df05e2f52)
