### ISSUE TITLE
Reduce disk write of 20+GB metadata file by filtering on the fly

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/forecasts-ncov#80]
### Context
Ingest runs quite slowly partially because it involves writing around 20GB to disk rather than streaming directly into tsv-filter here:
https://github.com/nextstrain/forecasts-ncov/blob/d051c57cdea7b174e6fcff9e890283a431a67879/ingest/rules/sequence_counts.smk#L6-L33

The two rules could be turned into one and do the filtering on the fly.

**Comment by joverlee521** [comment]
This will require updates to the vendored [download-from-s3](https://github.com/nextstrain/ingest/blob/a0faef53a0c6e7cc4057209454ef0852875dc3a9/download-from-s3) script to support streaming to stdout that can then be piped to tsv-filter.

**Comment by corneliusroemer** [comment]
Quick look suggests it might work with `/dev/stdout`?
